CREATE TABLE spotify_data (
    Track VARCHAR(500),
    AlbumName VARCHAR(500),
    Artist VARCHAR(500),
    ReleaseDate DATE,
    ISRC VARCHAR(500),
    AllTimeRank VARCHAR(500),
    TrackScore FLOAT,
    SpotifyStreams INT,
    SpotifyPlaylistCount VARCHAR(500),
    SpotifyPlaylistReach VARCHAR(500),
    SpotifyPopularity VARCHAR(500),
    YouTubeViews INT,
    YouTubeLikes VARCHAR(500),
    TiktokPosts VARCHAR(500),
    TikTokLikes VARCHAR(500),
    TikTokViews BIGINT,
    YouTubePlaylistReach VARCHAR(500),
    AppleMusicPlaylistCount VARCHAR(500),
    AirPlaySpins VARCHAR(500),
    SiriusXMSpins VARCHAR(500),
    DeezerPlaylistCount VARCHAR(500),
    DeezerPlaylistReach VARCHAR(500),	
    AmazonPlaylistCount VARCHAR(500),
    PandoraStreams INT,
    PandoraTrackStations VARCHAR(500),
    SoundcloudStreams VARCHAR(500),
    ShazamCounts VARCHAR(500),
    TIDALPopularity VARCHAR(500),
    ExplicitTrack INT
);

SELECT * FROM spotify_data